### ISSUE TITLE
fix or remove gpush_run_if_any

### ISSUE THREAD

**Issue by vccoffey** [nitidbit/gpush#11]
I think there is a bug in here.  But we can use the if: instead so maybe we can just remove it. But make sure no repos are using gpush_run_if_any in their gpushrc

**Comment by winstonwolff** [comment]
I think there are two bug:
- gpush_run_if_any doesn't properly find a subset of specs. It seems to run too many
- if any spec fails, that failure is not detected by gpush. I.e. it will think everything was OK, and push.

**Comment by mollycstark** [comment]
Running gpush --verbose will print the spec failures but the final output for Rspec shows 'SUCCESS'
Also buggy behavior when an rb file is deleted... look into further
