### ISSUE TITLE
feature request: search in directories up for gpushrc.yml

### ISSUE THREAD

**Issue by winstonwolff** [nitidbit/gpush#24]
Sometimes I'm in a sub-folder of my repo, e.g. lexicon/server, and I run `gpush`. There's a gpushrc.yml one directory up, but GPush doesn't find it, and runs it's default rules instead.

Desire: when I run gpush, search upwards in directories (up to the root of the file system?) for a gpushrc.

**Comment by winstonwolff** [comment]
It is correctly finding the gpushrc.yml file, but the pre_run commands are executed from the current directory. That causes the 'curl'ed files to be saved in the wrong place. It's a different bug though. Not sure what we should do about that--it's not obvious to me that executing the pre_run commands from the root is always wanted.

**Comment by vccoffey** [comment]
@winstonwolff the curl command could be updated to specify the local git root directory. Or, maybe it is better for all the commands to be run from the git root directory for consistency, what do you thing?

**Comment by winstonwolff** [comment]
Yeah, I was thinking all the commands should be run from the directory where the gpushrc.yml file is for consistency. I would think it unlikely that users would want anything else.

I could imagine some hypothetical other situations, but in all my years, I always want commands run from the project root.
