### ISSUE TITLE
Determine diff branch asked multiple times

### ISSUE THREAD

**Issue by vccoffey** [nitidbit/gpush#3]
When pushing to a new branch, gpush asks:

Could not `git diff` against origin/blah. What branch should I diff against to determine what you are going to push? [main] 

This question is asked multiple times. gpush_core should get the list of changed files once for `rspec_for_changed_files`, `scss_lint_for_changed_files`, etc. and cache the result.

**Comment by winstonwolff** [comment]
Fixed with this commit: f93c266
